<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="" host="WINDOWS-UNR7VLH"><DocLocation><![CDATA[C:\Hybrid Framework\Driver\Driver]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[Driver]]></DName>
<Res><![CDATA[Res8]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:23]]></Time>
<TimeTick>1678963583</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:23]]></Time>
<TimeTick>1678963583</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:24]]></Time>
<TimeTick>1678963584</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:24]]></Time>
<TimeTick>1678963584</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="13" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="12" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj ><![CDATA[Application Launch]]></Obj>
<Details ><![CDATA[Application launched successfully]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:24]]></Time>
<TimeTick>1678963584</TimeTick>
<NodeArgs eType="User" icon="7" nRep="14" status="Passed" >
<Disp><![CDATA[Application Launch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:25]]></Time>
<TimeTick>1678963585</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:25]]></Time>
<TimeTick>1678963585</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="17" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:25]]></Time>
<TimeTick>1678963585</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="19" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:25]]></Time>
<TimeTick>1678963585</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="21" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:26]]></Time>
<TimeTick>1678963586</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="22" >
<Disp><![CDATA[FIND FLIGHTS.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="16" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[Login Successfull]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:26]]></Time>
<TimeTick>1678963586</TimeTick>
<NodeArgs eType="User" icon="7" nRep="23" status="Passed" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:26]]></Time>
<TimeTick>1678963586</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:26]]></Time>
<TimeTick>1678963586</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="26" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:28]]></Time>
<TimeTick>1678963588</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="28" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="25" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj ><![CDATA[close the application]]></Obj>
<Details ><![CDATA[application closed unsuccessfully]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:28]]></Time>
<TimeTick>1678963588</TimeTick>
<NodeArgs eType="User" icon="7" nRep="29" status="Passed" >
<Disp><![CDATA[close the application]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:30]]></Time>
<TimeTick>1678963590</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:30]]></Time>
<TimeTick>1678963590</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="33" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="32" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:31]]></Time>
<TimeTick>1678963591</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:31]]></Time>
<TimeTick>1678963591</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="35" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="34" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj ><![CDATA[Application Launch]]></Obj>
<Details ><![CDATA[Application launched successfully]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:31]]></Time>
<TimeTick>1678963591</TimeTick>
<NodeArgs eType="User" icon="7" nRep="36" status="Passed" >
<Disp><![CDATA[Application Launch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:31]]></Time>
<TimeTick>1678963591</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:31]]></Time>
<TimeTick>1678963591</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="39" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:32]]></Time>
<TimeTick>1678963592</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="41" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:32]]></Time>
<TimeTick>1678963592</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="43" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:32]]></Time>
<TimeTick>1678963592</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="44" >
<Disp><![CDATA[FIND FLIGHTS.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="38" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[Login Successfull]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:32]]></Time>
<TimeTick>1678963592</TimeTick>
<NodeArgs eType="User" icon="7" nRep="45" status="Passed" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:33]]></Time>
<TimeTick>1678963593</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Denver"]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:33]]></Time>
<TimeTick>1678963593</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="48" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:33]]></Time>
<TimeTick>1678963593</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="50" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:33]]></Time>
<TimeTick>1678963593</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="52" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA[2, 1]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:34]]></Time>
<TimeTick>1678963594</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="54" >
<Disp><![CDATA[flightsDataGrid.SelectCell]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:34]]></Time>
<TimeTick>1678963594</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="56" >
<Disp><![CDATA[SELECT FLIGHT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[passengerName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["v"]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:34]]></Time>
<TimeTick>1678963594</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="58" >
<Disp><![CDATA[passengerName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[ORDER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:35]]></Time>
<TimeTick>1678963595</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="60" >
<Disp><![CDATA[ORDER.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:35]]></Time>
<TimeTick>1678963595</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="62" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:37]]></Time>
<TimeTick>1678963597</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="64" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="47" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj ><![CDATA[close the application]]></Obj>
<Details ><![CDATA[application closed unsuccessfully]]></Details>
<Time><![CDATA[16-03-2023 - 16:16:37]]></Time>
<TimeTick>1678963597</TimeTick>
<NodeArgs eType="User" icon="7" nRep="65" status="Passed" >
<Disp><![CDATA[close the application]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="16-03-2023 - 16:16:23" eTime="16-03-2023 - 16:16:41" passed="8" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T42">
<AName><![CDATA[Action2]]></AName>
<Summary sTime="16-03-2023 - 16:16:41" eTime="16-03-2023 - 16:16:41" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="67" >
<Disp><![CDATA[Action2 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T43">
<AName><![CDATA[Action3]]></AName>
<Summary sTime="16-03-2023 - 16:16:41" eTime="16-03-2023 - 16:16:41" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="69" >
<Disp><![CDATA[Action3 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T44">
<AName><![CDATA[Action4]]></AName>
<Summary sTime="16-03-2023 - 16:16:41" eTime="16-03-2023 - 16:16:41" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="71" >
<Disp><![CDATA[Action4 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[Driver Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="16-03-2023 - 16:16:21" eTime="16-03-2023 - 16:16:41" passed="8" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test Driver Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>